Добавил пару опций для возможности отправки в другое апи
skbkontur/serilog.LogglyBulkSink pull request #4
Opened 2018-01-25 13:27 UTC by AlexAkulov

2018-01-25 13:43 UTC, RawRCoder requested changes

2018-01-25 13:43 UTC, RawRCoder commented on Serilog.ELKBulkSink/SinkOptions.cs
> +        public bool AppendIndex { get; set; } = true;
В идеале, кажется, лучше забубенить что-то вроде `public Api Api {get;set;} = Api.Elk` где `Api` либо enum либо какой-то интерфейс, инстансы которого умели бы, скажем, отдавать фабрику WebRequest`ов. Ну и сделать пару реализаций, одну - как была раньше, и одну новую. + Можно в использующем коде делать свои.

2018-01-25 14:23 UTC, AlexAkulov commented on Serilog.ELKBulkSink/SinkOptions.cs
> +        public bool AppendIndex { get; set; } = true;
По мне так в идеале иметь только url, а IndexTemplate вообще выпилить.

2018-01-26 04:10 UTC, RawRCoder commented on Serilog.ELKBulkSink/SinkOptions.cs
> +        public bool AppendIndex { get; set; } = true;
Да, можно, наверное

2018-01-26 09:58 UTC, AlexAkulov commented
Ну, что? Мерджим?

2018-01-26 10:01 UTC, merged